# Generated by tools\gen_init.py

from .audio import AudioManager
from .filters import apply_fourier_filter, poly_ratio_H, rect_H, apply_convolution, apply_transform, eval_kernel, eval_H_expr
from .fourier import extract_contour, compute_dft, reconstruct_path
from .plots import PlotManager
from .signals import WAVE_FUNCS, parse_coeffs, custom_wave, samples_to_fourier_coeffs
from .STYLES import COLORS, FFT_PLOT_COLORS, SIGNAL_COLORS, SLIDER_LAYOUT, DD_LAYOUT, CB_LAYOUT, PLOT, SECTION_STYLE, FREQ_LABEL_STYLE, BLOCK_BORDER, BLOCK_LAYOUT, ARROW_HTML, FORMULA_STYLE, BLOCK_HEADER_STYLE_LG, BLOCK_HEADER_STYLE_SM
from .texrender import parse_poly, poly_to_latex, expr_to_latex
from .ui import section, dark_ax, plot_waveform_and_fft

__all__ = [
    "ARROW_HTML",
    "AudioManager",
    "BLOCK_BORDER",
    "BLOCK_HEADER_STYLE_LG",
    "BLOCK_HEADER_STYLE_SM",
    "BLOCK_LAYOUT",
    "CB_LAYOUT",
    "COLORS",
    "DD_LAYOUT",
    "FFT_PLOT_COLORS",
    "FORMULA_STYLE",
    "FREQ_LABEL_STYLE",
    "PLOT",
    "PlotManager",
    "SECTION_STYLE",
    "SIGNAL_COLORS",
    "SLIDER_LAYOUT",
    "WAVE_FUNCS",
    "apply_convolution",
    "apply_fourier_filter",
    "apply_transform",
    "compute_dft",
    "custom_wave",
    "dark_ax",
    "eval_H_expr",
    "eval_kernel",
    "expr_to_latex",
    "extract_contour",
    "parse_coeffs",
    "parse_poly",
    "plot_waveform_and_fft",
    "poly_ratio_H",
    "poly_to_latex",
    "reconstruct_path",
    "rect_H",
    "samples_to_fourier_coeffs",
    "section",
]
