import sys
import ast
from pathlib import Path

VENV_NAMES = {"venv", "env", ".venv", ".env"}


def find_defs(file_path):
    try:
        tree = ast.parse(file_path.read_text(encoding="utf-8"))
    except SyntaxError:
        return []
    return _collect_body(tree.body)


def _collect_body(body):
    entries = []
    for node in body:
        if isinstance(node, ast.ClassDef):
            children = _collect_body(node.body)
            entries.append(("class", node.name, children))
        elif isinstance(node, ast.FunctionDef) or isinstance(
            node, ast.AsyncFunctionDef
        ):
            children = _collect_body(node.body)
            entries.append(("def", node.name, children))
    return entries


def build_tree(base_dir):
    base_dir = base_dir.resolve()
    py_files = sorted(
        f
        for f in base_dir.rglob("*.py")
        if not any(part in VENV_NAMES for part in f.parts)
    )

    sections = {}
    for f in py_files:
        rel = f.relative_to(base_dir)
        entries = find_defs(f)
        if entries:
            sections[str(rel)] = entries

    return sections


def format_tree(sections):
    lines = [f"# Generated by {Path(__file__).resolve().relative_to(Path.cwd())}", ""]

    for rel_path, entries in sections.items():
        lines.append(f"## `{rel_path}`")
        lines.append("")
        _format_entries(entries, indent=0, lines=lines)
        lines.append("")

    return "\n".join(lines)


def _format_entries(entries, indent, lines):
    prefix = "  " * indent
    for kind, name, children in entries:
        if kind == "class":
            lines.append(f"{prefix}- **class** `{name}`")
        else:
            lines.append(f"{prefix}- `{name}()`")
        if children:
            _format_entries(children, indent + 1, lines)


def main():
    if len(sys.argv) > 2:
        print("Usage: python gen_tree.py")
        print("       python gen_tree.py <directory>")
        sys.exit(1)

    base_dir = Path.cwd()
    if len(sys.argv) == 2:
        base_dir = Path(sys.argv[1])
        if not base_dir.is_dir():
            print(f"Error: {base_dir} is not a directory")
            sys.exit(1)

    sections = build_tree(base_dir)
    md = format_tree(sections)

    docs_dir = base_dir / "docs"
    docs_dir.mkdir(exist_ok=True)
    output_path = docs_dir / "tree.md"
    output_path.write_text(md, encoding="utf-8")

    print(f"Generated {output_path}")


if __name__ == "__main__":
    main()
