import ast
import sys
from pathlib import Path


def extract_symbols(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        tree = ast.parse(f.read(), filename=str(file_path))

    names = []

    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if not node.name.startswith("_"):
                names.append(node.name)

        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and not target.id.startswith("_"):
                    names.append(target.id)

    return names


def main():
    if len(sys.argv) != 2:
        print("Usage: python -m gen_init <directory>")
        sys.exit(1)

    base_dir = Path(sys.argv[1]).resolve()

    if not base_dir.is_dir():
        print(f"Error: {base_dir} is not a directory")
        sys.exit(1)

    imports = []
    all_names = []

    for file in sorted(base_dir.glob("*.py")):
        if file.name == "__init__.py":
            continue

        module_name = file.stem
        symbols = extract_symbols(file)

        if not symbols:
            continue

        import_line = f"from .{module_name} import {', '.join(symbols)}"
        imports.append(import_line)
        all_names.extend(symbols)

    lines = []
    lines.extend(imports)
    lines.append("")
    lines.append("__all__ = [")

    for name in sorted(all_names):
        lines.append(f'    "{name}",')

    lines.append("]")

    lines.insert(0, f"# Generated by {Path(__file__).resolve().relative_to(Path.cwd())}\n")

    output_path = base_dir / "__init__.py"
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Generated {output_path}")


if __name__ == "__main__":
    main()